[versions]
java = "21"

node-gradle = "7.1.0"

spring-framework = "3.3.3"
spring-openapi-doc = "2.6.0"
spring-dependency-managment = "1.1.6"

# service APIs deps
common-api = "0.0.2"
localization-api = "0.0.7"
error-api = "0.0.16"
web-app-api = "0.0.6"


[libraries]
common-api = { module = "com.github.sibdevtools:api-common", version.ref = "common-api" }
localization-api = { module = "com.github.sibdevtools:api-localization", version.ref = "localization-api" }
error-api = { module = "com.github.sibdevtools:api-error", version.ref = "error-api" }
web-app-api = { module = "com.github.sibdevtools:api-web-app", version.ref = "web-app-api" }

spring-openapi-starter = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "spring-openapi-doc" }

[bundles]
service-api = [
    "common-api",
    "localization-api",
    "error-api",
    "web-app-api"
]

[plugins]
node-gradle = { id = "com.github.node-gradle.node", version.ref = "node-gradle" }
spring-framework-boot = { id = "org.springframework.boot", version.ref = "spring-framework" }
spring-dependency-managment = { id = "io.spring.dependency-management", version.ref = "spring-dependency-managment" }